services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_MP_PUBLIC_KEY: ${NEXT_PUBLIC_MP_PUBLIC_KEY}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    ports:
      - "3000:3000"
    environment:
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
    restart: unless-stopped
